AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
      Variables:
        APP_STORAGE: /tmp
Resources:
  Website:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: weather-forecast
      CodeUri: s3://madewithlove-exam-karen/4778db81d6b14ba767b1e4259c26e6eb
      Handler: public/index.php
      Timeout: 30
      Runtime: provided
      Layers:
      - arn:aws:lambda:ap-southeast-1:209497400698:layer:php-72-fpm:7
      Events:
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        Warmer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Input: '{"warmer": true}'
  Artisan:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: laravel-artisan
      CodeUri: s3://madewithlove-exam-karen/4778db81d6b14ba767b1e4259c26e6eb
      Handler: artisan
      Timeout: 120
      Runtime: provided
      Layers:
      - arn:aws:lambda:ap-southeast-1:209497400698:layer:php-72:7
      - arn:aws:lambda:ap-southeast-1:209497400698:layer:console:7
Outputs:
  DemoHttpApi:
    Description: URL of our function in the *Prod* environment
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
